# Generated by Django 5.1.3 on 2024-11-08 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('threats', '0004_alter_monthlyleakcount_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monthlyleakcount',
            name='count',
            field=models.IntegerField(default=0),
        ),
    ]
